# This is a basic workflow to help you get started with Actions

name: CI-22222

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "**" ]
    tags: ["test-*"]
  pull_request:
    branches: [ "jwx0925-*","master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multiply:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.step1.outputs.test }}
      strategy:
        matrix:
          param1: [100000000000000000000000d, 2000000000000000000000m]
          param2: [300000000000000000000000d, 4000000000000000000000f]
      steps:
      - name: Print multiplication result
        id: step1
        run: |
          echo "The result of ${{ matrix.param1 }} x ${{ matrix.param2 }}"
          echo "${{ matrix.param1 }}=${{ matrix.param2 }}" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: multiply
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
          echo ${{ needs.multiply.outputs.output1 }}
  build-0:
    runs-on: ubuntu-latest
    needs: multiply
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
  build-1:
    runs-on: ubuntu-latest
    needs: [build,multiply]
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
  build-2:
    runs-on: ubuntu-latest
    needs: [build-0,build-1]
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
