# This is a basic workflow to help you get started with Actions

name: CI-22222

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "**" ]
    tags: ["test-*"]
  pull_request:
    branches: [ "jwx0925-*","master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multiply:
      runs-on: ubuntu-latest
      outputs:
        output1: ${{ steps.step1.outputs.arm }}
        output2: ${{ steps.step1.outputs.x86 }}
      strategy:
        matrix:
          param1: [arm, x86]
          param2: [xixi, haha]
      steps:
      - name: Print multiplication result
        id: step1
        run: |
          echo "The result of ${{ matrix.param1 }} - ${{ matrix.param2 }}" 
          echo "${{ matrix.param1 }}=${{ matrix.param2 }}" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: multiply
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
          echo ${{ needs.multiply.outputs.output1 }}
          echo ${{ needs.multiply.outputs.output2 }}
  build-0:
    runs-on: ubuntu-latest
    needs: multiply
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
  build-1:
    runs-on: ubuntu-latest
    needs: [build,multiply]
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
  build-2:
    runs-on: ubuntu-latest
    needs: [build-0,build-1]
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - id: summary-1
        run: |
          echo Add other actions to build,
          echo "### Hello world222! :rocket:" >> $GITHUB_STEP_SUMMARY
      - id: summary-2
        run: |
          echo Add other actions to build,
          echo "### Hello world111! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "<button type="button" onclick=\"alert('Hello, World')\">点击我</button>" >> $GITHUB_STEP_SUMMARY
