# This is a basic workflow to help you get started with Actions

name: CI-22222

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "**" ]
    tags: ["test-*"]
  pull_request:
    branches: [ "jwx0925-*","master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  multiply:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          param1: [1, 2]
          param2: [3, 4]
      steps:
      - name: Print multiplication result
        run: echo "The result of ${{ matrix.param1 }} x ${{ matrix.param2 }} = $(( ${{ matrix.param1 }} * ${{ matrix.param2 }} ))"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, world!!!~~
      - run: |
          echo Add other actions to build,
          echo test, and deploy your project.111
